# Generated by Django 3.1.6 on 2021-02-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
