# Generated by Django 3.1.6 on 2021-02-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpApp', '0002_transaction_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='stock',
            field=models.CharField(max_length=10),
        ),
    ]
