# Generated by Django 3.1.6 on 2021-02-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpApp', '0003_auto_20210215_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='stock',
            new_name='stockID',
        ),
    ]
