# Generated by Django 3.1.6 on 2021-02-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpApp', '0005_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stockBalanceAsOnDate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
