# Generated by Django 3.1.6 on 2021-02-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpApp', '0006_transaction_stockbalanceasondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ops',
            field=models.CharField(default='Receipt', max_length=8),
            preserve_default=False,
        ),
    ]
